Shape and Reshape

In [1]:
import numpy as np
my_arr = np.array(input().split(),int)
print(np.reshape(my_arr,(3,3)))

1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


Transpose and flatten

In [6]:
n, m = map(int, input().split())
array = np.array([input().strip().split() for i in range(n)], int)
print (array.transpose())
print (array.flatten())

3 3
3
3
1 2 3
1 1 1
4 5 6
[[1 1 4]
 [2 1 5]
 [3 1 6]]
[1 2 3 1 1 1 4 5 6]


Concatenate

In [33]:
a, b, c = map(int,input().split())
arrA = np.array([input().strip().split() for _ in range(a)],int)
arrB = np.array([input().strip().split() for _ in range(b)],int)
print(np.concatenate((arrA, arrB), axis = 0))

2 3 1
1
2
3
3
4
[[1]
 [2]
 [3]
 [3]
 [4]]


**Zeros and Ones**
You are given the shape of the array in the form of space-separated integers, each integer representing the size of different dimensions, your task is to print an array of the given shape and integer type using the tools numpy.zeros and numpy.ones.

In [12]:
nums = tuple(map(int, input().split()))
print(np.zeros(nums, dtype = np.int))
print(np.ones(nums, dtype = np.int))


3 3 3
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


Eye and Identity

In [24]:
a, b = map(int,input().split())
print(np.eye(a, b))

3 3
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


You are given two integer arrays,  and  of dimensions X.
Your task is to perform the following operations:

Add (A + B )
Subtract (A - B )
Multiply (A * B )
Integer Division (A / B )
Mod (A % )
Power (A ** B )

In [26]:
n, m = map(int,input().split())
a = np.array([input().strip().split() for _ in range(n)],int)
b = np.array([input().strip().split() for _ in range(n)],int)
print(a+b, a-b, a*b, a//b, a%b, a**b, sep='\n')


1 4
1 2 3 4
5 6 7 8
[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[0 0 0 0]]
[[1 2 3 4]]
[[    1    64  2187 65536]]


Floor, Ceil and Rint

In [29]:
np.set_printoptions(sign = ' ')
my_arr = np.array(input().split(),float)
print(np.floor(my_arr))
print(np.ceil(my_arr))
print(np.rint(my_arr))

1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9
[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
[  2.   3.   4.   5.   6.   7.   8.   9.  10.]
[  1.   2.   3.   4.   6.   7.   8.   9.  10.]


Sum and Prod

In [30]:
import numpy as np
n, m = map(int,input().split())
a = np.array([input().strip().split() for _ in range(n)],int)
b=np.sum(a, axis = 0)
print (np.sum(a, axis = 0))
print (np.product(b))

2 2
1 2
3 4
[4 6]
24


PreparePythonNumpyMin and Max
Min and Max

In [31]:
n, m = map(int,input().split())
a = np.array([input().strip().split() for _ in range(n)],int)
b=np.min(a, axis = 0)
print (np.max(np.min(a, axis = 1)))

4 2
2 5
3 7
1 3
4 0
3


Mean, Var, and Std

In [32]:
n, m = map(int,input().split())
a = np.array([input().strip().split() for _ in range(n)],int)
print (np.mean(a, axis = 1))
print (np.var(a, axis = 0))
print (np.std(a))

2 2
1 2
3 4
[ 1.5  3.5]
[ 1.  1.]
1.118033988749895


Dot and Cross

In [ ]:
import numpy as np
n = int(input())
a = np.array([input().strip().split() for _ in range(n)],int)
b = np.array([input().strip().split() for _ in range(n)],int)
print(np.dot(a,b))
